version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password1234
      POSTGRES_DB: EcommerceDB
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  app:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      PGUSER: postgres
      PGHOST: postgres
      PGDATABASE: EcommerceDB
      PGPASSWORD: password1234
      PGPORT: 5432
      SEARCH_PATH: public

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - app

volumes:
  postgres-data:
